[package]
name = "text-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.20.2"
signal-hook = "0.3.17"
termion = "4.0.3"
termios = "0.3.3"

[dev-dependencies]
tempfile = "3.14.0"
